export type CountryCode = keyof typeof COUNTRY_CODE_MAPPING;

export const COUNTRY_CODE_MAPPING = {
	CA: 'Canada',
	HK: 'Hong Kong',
	MN: 'Mongolia',
	CY: 'Cyprus',
	PH: 'Philippines',
	BN: 'Brunei',
	HU: 'Hungary',
	MO: 'Macau',
	TH: 'Thailand',
	JO: 'Jordan',
	CH: 'Switzerland',
	RU: 'Russia',
	NO: 'Norway',
	AU: 'Australia',
	AT: 'Austria',
	VN: 'Vietnam',
	QA: 'Qatar',
	DZ: 'Algeria',
	GE: 'Georgia',
	IT: 'Italy',
	PL: 'Poland',
	ES: 'Spain',
	CN: 'China',
	MX: 'Mexico',
	SA: 'Saudi Arabia',
	GR: 'Greece',
	KH: 'Cambodia',
	BG: 'Bulgaria',
	SG: 'Singapore',
	CL: 'Chile',
	KZ: 'Kazakhstan',
	PT: 'Portugal',
	MY: 'Malaysia',
	DE: 'Germany',
	US: 'United States',
	FI: 'Finland',
	LK: 'Sri Lanka',
	TR: 'Turkey',
	JP: 'Japan',
	KE: 'Kenya',
	AR: 'Argentina',
	IN: 'India',
	CZ: 'Czech Republic',
	ZA: 'South Africa',
	FR: 'France',
	RS: 'Serbia',
	SD: 'Sudan',
	NZ: 'New Zealand',
	VU: 'Vanuatu',
	TW: 'Taiwan',
	MZ: 'Mozambique',
	GB: 'United Kingdom',
	IR: 'Iran',
	IE: 'Ireland',
	KW: 'Kuwait',
	IL: 'Israel',
	RO: 'Romania',
	KR: 'South Korea',
	NL: 'Netherlands',
	LU: 'Luxembourg',
	BE: 'Belgium',
	BR: 'Brazil',
	MV: 'Maldives',
	TBA: 'Papua New Guinea',
	BD: 'Bangladesh',
	PK: 'Pakistan',
	DK: 'Denmark',
	MM: 'Myanmar',
	HR: 'Croatia',
	AF: 'Afghanistan',
	AE: 'United Arab Emirates',
	SE: 'Sweden'
};
